"""m1 add user model

Revision ID: 18c1d668f8e6
Revises: 515469edae17
Create Date: 2026-09-18 08:09:14.214898

"""

# pyright: reportAttributeAccessIssue=false

from typing import Any, Sequence, Union, cast

from alembic import op
import sqlalchemy as sa

op = cast(Any, op)

# revision identifiers, used by Alembic.
revision: str = "18c1d668f8e6"
down_revision: Union[str, Sequence[str], None] = "515469edae17"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(  # type: ignore[attr-defined]
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=False),
        sa.Column("role", sa.Enum("buyer", "seller", "admin", name="user_role"), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("mpesa_phone", sa.String(length=32), nullable=True),
        sa.Column("mpesa_account_name", sa.String(length=120), nullable=True),
        sa.Column("session_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_phone"), "users", ["phone"], unique=True)  # type: ignore[attr-defined]
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)  # type: ignore[attr-defined]
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_role"), table_name="users")  # type: ignore[attr-defined]
    op.drop_index(op.f("ix_users_phone"), table_name="users")  # type: ignore[attr-defined]
    op.drop_table("users")  # type: ignore[attr-defined]
    # ### end Alembic commands ###
