"""m1 add dispute model

Revision ID: 41e88d21279e
Revises: 6f8c9a5af678
Create Date: 2026-09-18 08:49:28.983024

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "41e88d21279e"
down_revision: Union[str, Sequence[str], None] = "6f8c9a5af678"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "disputes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("transaction_id", sa.UUID(), nullable=False),
        sa.Column("opened_by_user_id", sa.UUID(), nullable=False),
        sa.Column(
            "dispute_type", sa.Enum("physical", "functional", name="dispute_type"), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "buyer_sent_back",
                "return_received",
                "awaiting_buyer_reconfirmation",
                "escalated_admin_review",
                "resolved_release",
                "resolved_refund",
                "resolved_split",
                "canceled",
                name="dispute_status",
            ),
            server_default=sa.text("'open'"),
            nullable=False,
        ),
        sa.Column("reason", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "seller_resolution_action",
            sa.Enum(
                "refund_issued",
                "repair_shipped",
                "replacement_shipped",
                name="seller_resolution_action",
            ),
            nullable=True,
        ),
        sa.Column(
            "admin_decision",
            sa.Enum("refund", "release", "split", name="admin_decision"),
            nullable=True,
        ),
        sa.Column("split_ratio", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column(
            "evidence",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("seller_resolution_notes", sa.Text(), nullable=True),
        sa.Column("admin_reason", sa.Text(), nullable=True),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("escalated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "split_ratio IS NULL OR (split_ratio > 0 AND split_ratio < 1)",
            name="ck_disputes_split_ratio_bounds",
        ),
        sa.ForeignKeyConstraint(["opened_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["transaction_id"], ["transactions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_disputes_dispute_type"), "disputes", ["dispute_type"], unique=False)
    op.create_index(
        op.f("ix_disputes_opened_by_user_id"), "disputes", ["opened_by_user_id"], unique=False
    )
    op.create_index(op.f("ix_disputes_status"), "disputes", ["status"], unique=False)
    op.create_index(
        op.f("ix_disputes_transaction_id"), "disputes", ["transaction_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_disputes_transaction_id"), table_name="disputes")
    op.drop_index(op.f("ix_disputes_status"), table_name="disputes")
    op.drop_index(op.f("ix_disputes_opened_by_user_id"), table_name="disputes")
    op.drop_index(op.f("ix_disputes_dispute_type"), table_name="disputes")
    op.drop_table("disputes")
    # ### end Alembic commands ###
