"""m1 add transaction model

Revision ID: 6f8c9a5af678
Revises: 29ebb64c360c
Create Date: 2026-09-18 08:38:41.695354

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "6f8c9a5af678"
down_revision: Union[str, Sequence[str], None] = "29ebb64c360c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transactions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("listing_id", sa.UUID(), nullable=False),
        sa.Column("buyer_id", sa.UUID(), nullable=False),
        sa.Column("seller_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "initiated",
                "locked",
                "dispatched",
                "at_door_pending_inspection",
                "hold_24h",
                "disputed_functional",
                "return_in_transit",
                "return_received",
                "awaiting_buyer_reconfirmation",
                "escalated_admin_review",
                "returned_to_seller",
                "released",
                "refunded_buyer",
                "resolved_release",
                "resolved_refund",
                "resolved_split",
                name="transaction_status",
            ),
            server_default=sa.text("'initiated'"),
            nullable=False,
        ),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dispatched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("at_door_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hold_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("refunded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("amount > 0", name="ck_transactions_amount_positive"),
        sa.CheckConstraint("buyer_id <> seller_id", name="ck_transactions_distinct_parties"),
        sa.ForeignKeyConstraint(["buyer_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["listing_id"], ["listings.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["seller_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_transactions_buyer_id"), "transactions", ["buyer_id"], unique=False)
    op.create_index(
        op.f("ix_transactions_listing_id"), "transactions", ["listing_id"], unique=False
    )
    op.create_index(op.f("ix_transactions_seller_id"), "transactions", ["seller_id"], unique=False)
    op.create_index(op.f("ix_transactions_status"), "transactions", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transactions_status"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_seller_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_listing_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_buyer_id"), table_name="transactions")
    op.drop_table("transactions")
    # ### end Alembic commands ###
