# pyright: reportAttributeAccessIssue=false

"""m2 add user sessions for login logout

Revision ID: 7843f7077a7a
Revises: 0a2f9a14c072
Create Date: 2026-09-19 14:14:31.002991

"""

from typing import Any, Sequence, Union, cast

from alembic import op as alembic_op
import sqlalchemy as sa

op: Any = cast(Any, alembic_op)

# revision identifiers, used by Alembic.
revision: str = "7843f7077a7a"
down_revision: Union[str, Sequence[str], None] = "0a2f9a14c072"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(  # type: ignore[attr-defined]
        "user_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("session_token_hash", sa.String(length=128), nullable=False),
        sa.Column("csrf_token_hash", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_user_sessions_expires_at", "user_sessions", ["expires_at"], unique=False)  # type: ignore[attr-defined]
    op.create_index("ix_user_sessions_revoked_at", "user_sessions", ["revoked_at"], unique=False)  # type: ignore[attr-defined]
    op.create_index(
        "ix_user_sessions_session_token_hash",
        "user_sessions",
        ["session_token_hash"],
        unique=True,
    )  # type: ignore[attr-defined]
    op.create_index("ix_user_sessions_user_id", "user_sessions", ["user_id"], unique=False)  # type: ignore[attr-defined]
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_sessions_user_id", table_name="user_sessions")  # type: ignore[attr-defined]
    op.drop_index("ix_user_sessions_session_token_hash", table_name="user_sessions")  # type: ignore[attr-defined]
    op.drop_index("ix_user_sessions_revoked_at", table_name="user_sessions")  # type: ignore[attr-defined]
    op.drop_index("ix_user_sessions_expires_at", table_name="user_sessions")  # type: ignore[attr-defined]
    op.drop_table("user_sessions")  # type: ignore[attr-defined]
    # ### end Alembic commands ###
