# pyright: reportAttributeAccessIssue=false

"""m2 add login lockout fields

Revision ID: b6a85a0894b4
Revises: 7843f7077a7a
Create Date: 2026-09-19 14:30:44.023845

"""

from typing import Any, Sequence, Union, cast

from alembic import op as alembic_op
import sqlalchemy as sa

op: Any = cast(Any, alembic_op)

add_column: Any = op.add_column  # type: ignore[attr-defined]
create_index: Any = op.create_index  # type: ignore[attr-defined]
drop_index: Any = op.drop_index  # type: ignore[attr-defined]
drop_column: Any = op.drop_column  # type: ignore[attr-defined]


# revision identifiers, used by Alembic.
revision: str = "b6a85a0894b4"
down_revision: Union[str, Sequence[str], None] = "7843f7077a7a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    add_column(
        "users",
        sa.Column(
            "failed_login_attempts",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
    )
    add_column("users", sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True))
    create_index("ix_users_locked_until", "users", ["locked_until"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    drop_index("ix_users_locked_until", table_name="users")
    drop_column("users", "locked_until")
    drop_column("users", "failed_login_attempts")
    # ### end Alembic commands ###
